version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/packer:full-1.6.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: validate packer template
          command: |
            packer validate ~/project/packer/template.json
