version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/packer:full-1.6.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: validate packer template
          command: |
            cd ~/project/packer
            packer validate template.json
      - run: 
          name: build packer image on digitalocean
          command: |
            cd ~/project/packer
            packer build template.json
    
  init:
    docker:
      - image: hashicorp/terraform:0.12.26
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: init
          command: |
            cd ~/project/terraform
            terraform init -input=false
      - persist_to_workspace:
          root: .
          paths: .
      
  plan:
    docker:
      - image: hashicorp/terraform:0.12.26
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: init
          command: |
            cd ~/project/terraform
            terraform plan -out=tfplan -input=false
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2.1
  honeypot:
    jobs:
      - build:
          filters:
            branches:
              only: [master]
      - init
      - plan
