version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/packer:full-1.6.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: validate packer template
          command: |
            cd ~/project/packer
            packer validate template.json
      - run: 
          name: build packer image on digitalocean
          command: |
            cd ~/project/packer
            packer build template.json
